#!/bin/bash

# List of metrics
metrics=("prop_vel" "sw_duration" "fw_duration" "event_interval" "fw_presence" "fw_delay")

# Loop over each metric and call Rscript
for metric in "${metrics[@]}"; do
    Rscript statistical-analysis.R uterine-electrophysiology/data/exports "$metric"
done

Rscript direction-analysis.R uterine-electrophysiology/data/exports
