function displayAnalysisStructureResults(AS)
%DISPLAYANALYSISSTRUCTURERESULTS Prints out the results of an analysis 
%structure. See createAnalysisStructure.m for more details on the contents
%of an AS.
%
%   Input:
%    - AS, analysis structure containing the analysis metrics, see
%    createAnalysisStruct.m for more details. 
valid_events = AS.nb_samples > 0;
nb_events = sum(valid_events);
nb_samples = AS.nb_samples(valid_events);

% Display results
disp(strcat("Experiment ID code: ", AS.name))
disp([' Number of events: ', num2str(nb_events)])
disp([' Event occurence rate: ', num2str(AS.EOR),  ' events/min']);
disp([' Average event interval: ', num2str( ...
    mean(AS.event_interval(1, AS.event_interval(1, :) > 0))), ...
    ' ± ', ...
    num2str(avgDeviation( ...
        AS.event_interval(2, AS.event_interval(2, :) > 0), ...
        AS.event_interval(3, AS.event_interval(3, :) > 0) ...
        )), ...
    ' s'
    ]);

% Propagation properties
disp(' Propagation properties');
disp(['  Average propagation velocity: ', num2str(mean(...
    AS.prop_vel(valid_events))), ...
    ' ± ', num2str(std(AS.prop_vel(valid_events))), ' mm/s']);
disp(['  Average propagation distance: ', num2str(mean( ...
    AS.prop_dist(valid_events))), ...
    ' ± ', num2str(std(AS.prop_dist(valid_events))), ' mm']);
disp('  Propagation direction:');
disp(['   Ovaries -> cervix: ', num2str( ...
    100*sum(AS.prop_direction(valid_events) > 0) / nb_events), ' %']);
disp(['   Cervix -> ovaries: ', num2str( ...
    100*sum(AS.prop_direction(valid_events) < 0) / nb_events), ' %']);
disp(['   Disorganised: ', num2str( ...
    100*sum(AS.prop_direction(valid_events) == 0) / nb_events), ' %']);
% Slow-wave properties
disp(' Slow-wave properties');
disp(['  Average event duration: ', ...
    num2str(mean(AS.sw_duration(1, valid_events))), ' ± ', num2str( ...
    avgDeviation(AS.sw_duration(2, valid_events), nb_samples)), ' s'])
% disp(['  Average max frequency: ', ...
%     num2str(mean(AS.sw_frequency(1, valid_events))), ' ± ', num2str( ...
%     avgDeviation(AS.sw_frequency(2, valid_events), nb_samples)), ' Hz'])

% Fast-wave properties
disp(' Fast-wave properties');
disp(['  Average event duration: ', ...
    num2str(mean(AS.fw_duration(1, valid_events))), ' ± ', num2str( ...
    avgDeviation(AS.fw_duration(2, valid_events), nb_samples)), ' s'])
disp(['  Average delay: ', ...
    num2str(mean(AS.fw_delay(1, valid_events))), ' ± ', num2str( ...
    avgDeviation(AS.fw_delay(2, valid_events), nb_samples)), ' s'])
disp(['  Average bursting percent: ', num2str(mean( ...
    AS.fw_percentage(valid_events))), ...
    ' ± ', num2str(std(AS.fw_percentage(valid_events))), ' %']);
% disp(['  Average max frequency: ', ...
%     num2str(mean(AS.fw_frequency(1, valid_events))), ' ± ', num2str( ...
%     avgDeviation(AS.fw_frequency(2, valid_events), nb_samples)), ' Hz'])
% disp(['  Average 95% power frequency band: ', ...
%     num2str(mean(AS.fw_bandwidth(1, valid_events))), ' ± ', num2str( ...
%     avgDeviation(AS.fw_bandwidth(2, valid_events), nb_samples)), ' Hz'])
% disp(['  Average low frequency band limit: ', ...
%     num2str(mean(AS.fw_flow(1, valid_events))), ' ± ', num2str( ...
%     avgDeviation(AS.fw_flow(2, valid_events), nb_samples)), ' Hz'])
% disp(['  Average high frequency band limit: ', ...
%     num2str(mean(AS.fw_fhigh(1, valid_events))), ' ± ', num2str( ...
%     avgDeviation(AS.fw_fhigh(2, valid_events), nb_samples)), ' Hz'])
end
