run_nb=3  # Experimental run number
transition=0
start_time=230  # Time at which to start the analysis
end_time=530  # Time at which to end the analysis
win_size=40  # Size of the observation window of an event in seconds
win_split=0.5  # Percentage of the window before the event timestamp
lowpass_cutoff_freq=0.5  # Hz
highpass_cutoff_freq=[1, 5]  # Hz
min_nb_chns=15  # Minimum number of channels needed to analyse event
