[phases]
    proestrus=["AWA031","AWA026", "AWB018", "AWB009"] 
    estrus=["AWA033", "AWB017", "AWB010", "AWB019"]
    metestrus=["AWB008", "AWB001", "AWB005", "AWB013"]
    diestrus=["AWA032", "AWB003", "AWB004", "AWB012"]
