run_nb=3  # Experimental run number
start_time=80  # Time at which to start the analysis
end_time=380  # Time at which to end the analysis
win_size=30  # Size of the observation window of an event in seconds
win_split=0.25  # Percentage of the window before the event timestamp
lowpass_cutoff_freq=1  # Hz
highpass_cutoff_freq=1  # Hz
min_nb_chns=15  # Minimum number of channels needed to analyse event
time_res=2  # Temporal resolution for spectrographic analysis
env_tolerance=0.12  # Percentage of the signal length to be used for calculating the RMS envelope
conn_tolerance=0.05  # Percentage of the signal length to be used for calculating the event connections
min_peak_dist=50  # Minimum peak distance for the annotationPlot.m function
